services:
  expensetracker:
    image: expense-tracker
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5068:5068
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5068
